tasks:
  - before: docker-compose -f src/main/docker/postgresql.yml up -d
    init: mvn install spring-boot:start spring-boot:stop
    command: mvn spring-boot:run
  #command: docker-compose -f src/main/docker/postgresql.yml up -d
  
ports:
  - port: 8080
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
github:
  prebuilds:
    master: true
vscode:
  extensions:
    - runem.lit-plugin@1.1.10:/yk3Arh4MIQ3RwIcHwbX3Q==