name: Java CI
on: 
  push:
      branches:
        - develop
        - '**/feature.*/'
        - master
jobs:       
    job9:
      name: job9 Publish package to the Artifactory Repository and GitHub Packages
      #needs: job7
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
      #   - name: Set up Java for publishing to Artifactory Repository
     #      uses: actions/setup-java@v1
       #    with:
      #       java-version: 1.8
        #     server-id: snapshots
        #     server-username: MAVEN_USERNAME
         #    server-password: MAVEN_PASSWORD
         #- name: Publish to my Artifactory Repository
         #  run: mvn -B deploy
          # env:
         #    MAVEN_USERNAME: ${{ secrets.JFROG_OSS_REPO_USER }}
          #   MAVEN_PASSWORD: ${{ secrets.JFROG_OSS_REPO_PASS }}
        
        - name:  Publishing my Artifactory Repository by overriding settings.xml
          run : |
            echo move settings. xml into .m2
            pwd 
            ls -l  src/main/settings/
            mv src/main/settings/settings.myartifactory.xml ~/.m2/settings.xml
        - name: Publish to my Artifactory Repository
          run: mvn -B deploy
        - name: Set up Java for publishing to GitHub Packages
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Publish to GitHub Packages
          run: mvn -B deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


            

    
    
        
      



    
